pipeline:
  test:
    image: python:3.5.2
    environment:
      - DJANGO_SETTINGS_MODULE=init_django.settings.dev
    commands:
      - pip install --upgrade setuptools
      - pip install -U pip==9.0.3
      #- pip install --upgrade pip
      - pip install tox
      #- make env
      #- make dev
      - pip install -r base.pip
      - make run
      - pytest

  
  slack:
     image: plugins/slack
     webhook: https://hooks.slack.com/services/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
     channel: developers
     username: pkumar2
     when:
       status: [ success, changed, failure ]       
     template: |
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} {{build.link_url}} failed. Fix me please.
      {{/success}}

